server:
  port: 8086 # AIæœåŠ¡ç«¯å£

spring:
  application:
    name: hksc-ai
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  # ğŸ‘‡ğŸ‘‡ğŸ‘‡ æ ¸å¿ƒï¼šå¼€å¯ JDK 21 è™šæ‹Ÿçº¿ç¨‹ ğŸ‘‡ğŸ‘‡ğŸ‘‡
  threads:
    virtual:
      enabled: true