server:
  port: 8082  # ç”¨æˆ·æœåŠ¡å ç”¨ 8082 ç«¯å£

spring:
  application:
    name: hksc-user  # åå­—å¿…é¡»å’Œ Nacos ä¸Šæ–°å»ºçš„é…ç½®åä¸€è‡´
  profiles:
    active: dev      # æ¿€æ´» dev ç¯å¢ƒ
  cloud:
    nacos:
      config:
        server-addr: localhost:8848 # Nacos åœ°å€
        file-extension: yaml
  # ğŸ‘‡ğŸ‘‡ğŸ‘‡ æ ¸å¿ƒæŠ¥é”™åŸå› ï¼šSpring Boot 3 å¿…é¡»åŠ è¿™å‡ è¡Œæ‰èƒ½è¿ Nacos é…ç½®ä¸­å¿ƒ ğŸ‘‡ğŸ‘‡ğŸ‘‡
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}