server:
  port: 8085

spring:
  application:
    name: hksc-cart
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:hksc-service-dev.yaml

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848