version: '3.8'

services:
  # 1. Nacos (æ›´æ¢ä¸º v2.2.3 ä»¥é¿å¼€æŸåçš„ç¼“å­˜å±‚)
  hksc-nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: hksc-nacos
    environment:
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
        # nacosé…ç½®æŒä¹…åŒ–åˆ°mysqlä¸­
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=hksc-mysql      # è¿™é‡Œçš„åå­—å¿…é¡»å’Œä¸‹é¢ MySQL çš„ service åå­—ä¸€è‡´
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root        # å¯¹åº”ä½  MySQL çš„ root å¯†ç 
      - MYSQL_SERVICE_PORT=3306            # ğŸ”´ æ³¨æ„ï¼å®¹å™¨å†…éƒ¨äº’è”ç”¨ 3306ï¼Œä¸æ˜¯ 3307
      -
         MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false

    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos/logs:/home/nacos/logs
    networks:
      - hksc-net

  # 2. MySQL (æ”¹ç”¨å­—å…¸æ ¼å¼é…ç½®ç¯å¢ƒå˜é‡)
  hksc-mysql:
    image: mysql:8.0
    container_name: hksc-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql_new:/var/lib/mysql # ä¿®æ”¹æŒ‚è½½è·¯å¾„ï¼Œç¡®ä¿é‡æ–°åˆå§‹åŒ–
    networks:
      - hksc-net

  # 3. Redis
  hksc-redis:
    image: redis:7.0
    container_name: hksc-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - hksc-net

  # 4. RabbitMQ
  hksc-rabbitmq:
    image: rabbitmq:3.12-management
    container_name: hksc-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - hksc-net

  hksc-es:
    image: elasticsearch:8.1.0
    container_name: hksc-es
    ports:
      - "9200:9200"
      - "9300:9300"


networks:
  hksc-net:
    driver: bridge
volumes:
  nacos_data: