server:\n  port: 8085\nspring:\n  datasource:\n    url: jdbc:mysql://localhost:3307/hksc_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true\n\nfeign:\n  sentinel:\n    enabled: true\n\n    
