server:
  port: 8084

spring:
  application:
    name: hksc-order
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
    sentinel:
      transport:
        dashboard: localhost:8858  # æ§åˆ¶å°åœ°å€
        port: 8719                 # äº¤äº’ç«¯å£
        # ğŸ‘‡ğŸ‘‡ğŸ‘‡ æ ¸å¿ƒæ£€æŸ¥ç‚¹ï¼šè¿™è¡Œè¿˜åœ¨å—ï¼Ÿå›é€€è‚¯å®šæŠŠå®ƒå¼„æ²¡äº†ï¼ ğŸ‘‡ğŸ‘‡ğŸ‘‡
        client-ip: 127.0.0.1
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}


feign:
  sentinel:
    enabled: true