spring:
  application:
    name: hksc-order
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:hksc-common.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  cloud:
    nacos:
      server-addr: localhost:8848